### ISSUE TITLE
slides over webslides

### ISSUE THREAD

**Issue by cljansse** [OpenWebslides/ICT-Lerarenopleiding#1]
Kan je nog slides over webslides aan de presentatie toevoegen. Dingen zoals, wat zijn webslides, wat zijn voordelen, wat zijn de tools die ze bieden,...

**Comment by EstherDeLoof** [comment]
For the time being, the slides from march 14th have been added, but I would like to make a selection in these slides. 
In order to make that selection, I have made a new repository with a copy of the slides from march 14th. This repository is also in the OpenWebSlides organization. https://github.com/OpenWebSlides/WebslidesDemoLerarenopleiding

The slides there have been selected and I would like to embed them in the presentation of Jo. However, I don't know how I should generate a webpage correctly. @RubenVerborgh can you help us out?

**Comment by RubenVerborgh** [comment]
Use the `gh-pages` branch instead of `master` and you'll get a website 😉

**Comment by EstherDeLoof** [comment]
Got it, fixed!
